### Update an existing entity
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "John Doe",
  "email": "emailvalidationcheck@gmail.com",
  "address": "123 main street New York",
  "dateOfBirth": "1996-09-09"
}
###